### ISSUE TITLE
vertically align = and -> in pattern matching

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/hindent#324]
I'm not sure if this is intentional. This code:

``` haskell
ex1 :: Bool -> Int
ex1 True  = 5
ex1 False = 3

ex2 :: Bool -> Int
ex2 x = case x of
  True  -> 5
  False -> 3
```

Gets reformatted to:

``` haskell
ex1 :: Bool -> Int
ex1 True = 5
ex1 False = 3

ex2 :: Bool -> Int
ex2 x =
  case x of
    True -> 5
    False -> 3
```

In Johan's guide it [says](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#case-expressions) "Align the `->` arrows when it helps readability." At least in my experience the majority of Haskell is written with vertically aligned pattern matches. The variables are usually aligned too.

**Comment by tfausak** [comment]
I'm not a fan of this style. As soon as one branch changes, every other line has to change to fix the alignment.

**Comment by wiz** [comment]
This can be difficult to get right. But at least hindent can preseve v-align where it is already in place.

**Comment by IvanMalison** [comment]
@tfausak Yeah but since hindent would (hypothetically) handle this automatically, why does that matter?

Are you worried about source control blame/diff sizes? Users who DON'T use hindent?

**Comment by tfausak** [comment]
@IvanMalison I am worried about both of those things. Also the heuristics for aligning things can be difficult. For example, should this be aligned?

``` hs
f Short                  = 0
f AReallyLongConstructor = 1
```

I don't think that is easier to read.

**Comment by wiz** [comment]
```haskell
f Short = 0
f AReallyLongConstructor = 1
f MerelyLong = 2
f AnotherPrettyCons = 3
```

On the other hand, I find this more difficult to follow values while scanning...

**Comment by calvertvl** [comment]
TL;DR: I summarize the existing discussion with some elaboration of my own, then suggest adding an option named ``align-maximum`` to define a tolerance used to determine whether v-align is applied or not:
```` yaml
align-maximum: -1 # current behavior (no v-align)
align-maximum: 0 # always v-align
align-maximum: N # only v-align if it is more than N characters from aligned
````
-----
@enolan, @tfausak, and @wiz have raised some very good points which I have summarized below, with some added comments (as sub-bullets):
* Vertical alignment is very common in available Haskell code.
    * Arguably v-align should be the default in hindent, or users will see odd output and are more likely to decide that hindent is mostly useless.
* Adding/changing a branch can break alignment, causing whitespace changes on multiple lines, and multi-line whitespace changes cause artifacts in diffs and blame.
    * V-alignment is something maintainers _may_ want to avoid, and it is possible that not being able to do so in hindent would cause them to not use a code formatter at all, which would also prevent their contributors from doing so.
* There is apparently some concern about users who do _not_ use hindent.
    * No reasoning was supplied; I can't come up with a convincing reason to worry about this beyond an "opinionated default = lost users" argument.
* Un-aligned is often more difficult to read, but for some users/circumstances aligned is more difficult to read.
    * IMO difficult-to-read aligned code usually means you need to refactor or your names/patterns are too long; I find v-aligned code to be much easier to read in nearly all cases.
* An heuristic to detect and preserve v-align was suggested, but it was noted that this can be difficult.
    * I would argue that for stability, clarity, and speed, we should prefer a formatting operation that can be done based purely on configuration and the AST without any need for separate parsing of the source file to detect pre-existing formatting.

An additional reason of my own:
* If a project's style guidelines are compatible with hindent, then I am more likely to contribute code to that project even if I hate the indentation style used (assuming that hindent supports my own preferred indentation style).

Normally I would argue against adding another option as I generally prefer sensible defaults, and option proliferation IMO tends to result in insensible defaults, but in this case I think it is warranted.

I suggest adding an option, allowing for the flexibility to choose between:
1. Align ``=`` and ``->`` if they would be more than N apart
    * I would prefer a default of N=0 (forced v-align), though 2 might be a reasonable compromise; I generally find differences of more than 3-4 to be significantly more difficult to follow.
1. Never align
    * Preserving this (current behavior) so maintainers who wish can use an un-aligned format does have value.

Suggested option name and values/comments:
```` yaml
align-maximum: 0   # always align, suggested default matching apparent community standard
align-maximum: -1  # preserves current behavior - disable v-align or use (line-length - 1)
align-maximum: N # configurable such that align-maximum is the allowed difference
    # in horizontal position, and exceeding this value forces vertical alignment
````
